/**
 * One-time setup for MPP Charge mode testnet testing.
 * Generates a recipient (server) and payer (client) keypair, funds both
 * via Friendbot, and adds a USDC trustline to both. Writes a starter
 * .env with the two secrets — you still need to do two manual web steps
 * afterward (Circle USDC faucet + OZ Channels API key).
 *
 * Run once: npx tsx packages/core/test/manual/setup-mpp-testnet.ts
 */
import fs from "node:fs/promises";
import {
  Keypair,
  Horizon,
  Networks,
  TransactionBuilder,
  Operation,
  Asset,
  BASE_FEE,
} from "@stellar/stellar-sdk";

// Circle's classic USDC issuer on Stellar testnet
const USDC_ISSUER = "GBBD47IF6LWK7P7MDEVSCWR7DPUWV3NY3DTQEVFL4NAT4AQH3ZLLFLA5";
const horizon = new Horizon.Server("https://horizon-testnet.stellar.org");

async function friendbot(addr: string): Promise<void> {
  const res = await fetch(`https://friendbot.stellar.org?addr=${addr}`);
  if (!res.ok) {
    throw new Error(`Friendbot funding failed for ${addr}: ${res.status} ${await res.text()}`);
  }
}

async function addTrustline(kp: Keypair): Promise<void> {
  const acc = await horizon.loadAccount(kp.publicKey());
  const tx = new TransactionBuilder(acc, {
    fee: BASE_FEE,
    networkPassphrase: Networks.TESTNET,
  })
    .addOperation(
      Operation.changeTrust({
        asset: new Asset("USDC", USDC_ISSUER),
      }),
    )
    .setTimeout(60)
    .build();
  tx.sign(kp);
  await horizon.submitTransaction(tx);
}

async function main() {
  console.log("Generating recipient (server) and payer (client) keypairs...");
  const recipient = Keypair.random();
  const payer = Keypair.random();

  console.log("Funding both via Friendbot...");
  await Promise.all([friendbot(recipient.publicKey()), friendbot(payer.publicKey())]);

  // Give the ledger a moment to settle account creation before submitting
  // the trustline transaction against it.
  await new Promise((r) => setTimeout(r, 3000));

  console.log("Adding USDC trustline to both accounts...");
  await addTrustline(recipient);
  await addTrustline(payer);

  const envPath = ".env";
  const envContent = `# --- MPP Charge mode testnet setup (generated by setup-mpp-testnet.ts) ---
MPP_STELLAR_NETWORK=stellar:testnet
MPP_RECIPIENT=${recipient.publicKey()}
MPP_PAYER_SECRET=${payer.secret()}
# Fill in manually — see console output below for links:
OZ_API_KEY=
MPP_SECRET_KEY=
`;
  await fs.appendFile(envPath, envContent);

  console.log("\nDone. Appended MPP testnet config to .env.");
  console.log(`\nRecipient (server):  ${recipient.publicKey()}`);
  console.log(`Payer (client):      ${payer.publicKey()}`);
  console.log("\nRemaining manual steps:");
  console.log(`1. Fund the PAYER with testnet USDC: https://faucet.circle.com/  (select Stellar testnet, paste ${payer.publicKey()})`);
  console.log("2. Generate an OZ Channels testnet API key: https://channels.openzeppelin.com/testnet/gen");
  console.log("   -> paste into OZ_API_KEY in .env");
  console.log("3. Set MPP_SECRET_KEY in .env to any random shared secret string (used for mppx credential verification, not a Stellar key)");
}

main().catch((err) => {
  console.error("Setup failed:", err);
  process.exit(1);
});
